const data = {
  products: [
    {
      _id: '1',
      name: 'Fusce dictum finibus',
      category: 'Shirts',
      image: '../img/gallery/01.jpg',
      price: '$45 / $55',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'Nam in suscipit nisi, sit amet consectetur metus. Ut sit amet tellus accumsan',
    },
    {
      _id: '2',
      name: 'Aliquam sagittis',
      category: 'Shirts',
      image: '../img/gallery/02.jpg',
      price: '$65 / $70',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'Nam in suscipit nisi, sit amet consectetur metus. Ut sit amet tellus accumsan',
    },
    {
      _id: '3',
      name: 'Sed varius turpis',
      category: 'Shirts',
      image: '../img/gallery/03.jpg',
      price: '$30.50',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'Nam in suscipit nisi, sit amet consectetur metus. Ut sit amet tellus accumsan',
    },
    {
      _id: '4',
      name: 'Aliquam sagittis',
      category: 'Shirts',
      image: '../img/gallery/04.jpg',
      price: '$25.50',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'Nam in suscipit nisi, sit amet consectetur metus. Ut sit amet tellus accumsan',
    },
    {
      _id: '5',
      name: 'Maecenas eget justo',
      category: 'Shirts',
      image: '../img/gallery/05.jpg',
      price: '$80.25',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'Nam in suscipit nisi, sit amet consectetur metus. Ut sit amet tellus accumsan',
    },
    {
      _id: '6',
      name: 'Quisque et felis eros',
      category: 'Shirts',
      image: '../img/gallery/06.jpg',
      price: '$20 / $40 / $60',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'Nam in suscipit nisi, sit amet consectetur metus. Ut sit amet tellus accumsan',
    },
    {
      _id: '7',
      name: 'Sed ultricies dui',
      category: 'Shirts',
      image: '../img/gallery/07.jpg',
      price: '$94',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'Nam in suscipit nisi, sit amet consectetur metus. Ut sit amet tellus accumsan',
    },
    {
      _id: '8',
      name: 'Donec porta consequat',
      category: 'Shirts',
      image: '../img/gallery/08.jpg',
      price: '$15',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'Nam in suscipit nisi, sit amet consectetur metus. Ut sit amet tellus accumsan',
    },
  ]
  }

  export default data;